### PR TITLE
fixed error in host.Init

### PR DESCRIPTION
**Pull request by alexlansovich**
Fixed error  undefined: hostInit

### CODE REVIEW

**Comment by alexlansovich** [comment]
Fixed error undefined: hostInit

**Comment by maruel** [comment]
This proposed change seems incorrect.

`hostInit()` is either defined in `host.go` or `hostextra.go` depending if the go build tag `periphextra` is defined. Please see the files in https://github.com/google/periph/tree/master/cmd/onewire-list.

**Comment by alexlansovich** [comment]
> This proposed change seems incorrect.
> 
> `hostInit()` is either defined in `host.go` or `hostextra.go` depending if the go build tag `periphextra` is defined. Please see the files in https://github.com/google/periph/tree/master/cmd/onewire-list.

I understand, but this example code cmd/onewire-list/main.go don't work without this

**Comment by maruel** [comment]
Can you expand on what you mean by "example code" ? This is a tool made of 3 source files. 

If you create a new tool based on its source you will have to modify it, but the tool itself works as-is.

**Comment by alexlansovich** [comment]
> Can you expand on what you mean by "example code" ? This is a tool made of 3 source files.
> 
> If you create a new tool based on its source you will have to modify it, but the tool itself works as-is.

I thought that one file would work :) You can delete all conversation as my mistake

**Comment by maruel** [comment]
No worries.

**Pull request closed without merging**
