### PR TITLE
Move the bmp180 cmd into experimental

### PR DESCRIPTION
**Pull request by maxekman**
It looks like this cmd was forgotten when the experimental folder became more structured.

### CODE REVIEW

**Comment by maruel** [comment]
ah and we also had forgot to add it to https://github.com/google/periph/blob/master/cmd/README.md.

I'll merge this but I think I've received the two I ordered (lost somewhere in my stack of junk) so we should write a smoke test and unit test and we could migrate this back into non-experimental soonish.

**Comment by maxekman** [comment]
Perfect, let me fix the readme first.

**Comment by maruel** [comment]
@fd0 fyi.

**Comment by maxekman** [comment]
Ok, nvm :)

**Comment by fd0** [comment]
Thanks!

**Pull request merged**
