### PR TITLE
rename device to peripheral

### PR DESCRIPTION
**Pull request by maruel**
Unsure if it's a good idea

### CODE REVIEW

**Comment by maruel** [comment]
The main challenge is to have consistent naming convention, so users can have a clearer picture.

Peripherals fits more with the project name "periph" and also is a clearer contrast with "host". On the other hand renaming the packages will break everyone but I'm willing to accept that, if I'm going to go ahead with this, the sooner the better.

**Comment by maruel** [comment]
Then there's the challenge with `Dev` and `DevParams`. My take is to rename `DevParams` to `PeripheralParams` but not touch `Dev`. Very undecided about it.

**Comment by tve** [comment]
I didn't look through the PR with a fine-toothed comb, but as far as I can tell it makes a lot of sense. It's odd at times, like calling the bme280 a peripheral. Or the one-wire lingo is "1-wire devices" and so it's odd to see "1-wire peripheral" instead.
In my mind the main pro is that it's clean and distinguishes linux devices vs. the, ahem, peripherals we actually want to program using this library. The main con is that perhaps it's too odd & pedantic.
Some additional opinions would be good, as well as perhaps looking at how the general docs would read.

**Comment by maruel** [comment]
I'll close this PR, as I'm not sure it's worth.

**Pull request closed without merging**
